//MAKE MODAL APPEAR ON LOAD
//MAKE MODAL DISAPPEAR ON SUBMIT CLICK (hint, you'll be using the CSS visibility property)
//MAKE MODAL DISAPPEAR ON X CLICK

//EXTRA: IF SUBMIT IS CLICKED, MAKE A CONFIRMATION MODAL APPEAR
